### ISSUE TITLE
ImportError: cannot import name 'override' from 'typing'

### ISSUE THREAD

**Issue by realsbd** [tomasemilio/FastAPI-Boilerplate#6]
after following the read.me i got this error when I run `python run.py`

```
PS C:\Users\DELL\Desktop\FastAPI-Boilerplate> python .\run.py        
INFO:     Will watch for changes in these directories: ['C:\\Users\\DELL\\Desktop\\FastAPI-Boilerplate']
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [19276] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\env\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\__init__.py", line 4, in <module>
    from app.api import router as api_router
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\api\__init__.py", line 5, in <module>
    from app.api.v1 import router as v1_router
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\api\v1\__init__.py", line 6, in <module>
    from app.api.v1.routes.admin import router as admin_router
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\api\v1\routes\admin.py", line 3, in <module>
    from app.api.v1.routes.user import request_reset_password
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\api\v1\routes\user.py", line 7, in <module>
    from app.models.auth.functions import authorize_and_load
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\models\auth\functions.py", line 12, in <module>
    from app.models.auth.schemes import oauth2_scheme
  File "C:\Users\DELL\Desktop\FastAPI-Boilerplate\app\models\auth\schemes.py", line 1, in <module>
    from typing import override
ImportError: cannot import name 'override' from 'typing' (C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\typing.py)
```

![image](https://github.com/user-attachments/assets/c5caff6c-a69b-4629-9a2b-4546340685cd)

**Comment by tomasemilio** [comment]
Hi. You are using Python 3.11. 
Try using python 3.12 or above or just get rid of the override and its imports. 

Let me know how it goes.

**Comment by realsbd** [comment]
> Hi. You are using Python 3.11. Try using python 3.12 or above or just get rid of the override and its imports.
> 
> Let me know how it goes.

It works now, but I switched the database to MySQL in this format but the data are not showing in my db
```
class Config(BaseConfig):
    DB_URL: str = "mysql+aiomysql://root:''@localhost/bicxchange"
    SECRET_KEY: str = "123"
    ALGORITHM: str = "HS512"
    TOKEN_EXPIRE_SECONDS: int = 3600
    RESET_EXPIRE_SECONDS: int = 300
    TOKEN_PATH: str = "api/v1/auth/token"
    ADMIN_EMAIL: EmailStr = "admin@sample.com"
    ADMIN_PASSWORD: str = "123"
    ADMIN_EMAIL_TOKEN: str = "123"
    LOG_LEVEL: str = "DEBUG"
    RATE_LIMITS: tuple[int, int] = (10, 60)
```

**Comment by tomasemilio** [comment]
Do you get any errors? I need more details to troubleshoot this. Thanks!

**Comment by realsbd** [comment]
how can i use another db like postgres or MySQL?

**Comment by tomasemilio** [comment]
```bash
postgresql+asyncpg://localhost/postgres
```
Here is an example. Or a remote DB as well. all the dependencies for postgres are in fact in the `requirements.txt`

I am going to close this issue since the original question was about the runtime version, but I am happy to keep discussing any questions you have.
